import React,{useEffect,useRef,useState} from "react";

const SPEEDS=[0,0.5,1,2,4,8];
const countries=[["GBR","United Kingdom"],["FRA","France"],["DEU","Germany"],["ITA","Italy"],["ESP","Spain"],["USA","United States"],["JPN","Japan"],["SOV","Soviet Union"]];
const buildings=[["factory","Industrial Plant"],["farm","Agricultural Estate"],["power","Power Station"],["university","University"],["barracks","Barracks"]];
const techs=[["assembly","Assembly Lines"],["public_health","Public Health"],["motorization","Motorization"],["electrification","National Electrification"],["combined_arms","Combined Arms"],["logistics","Modern Logistics"]];
const panel={position:"fixed",top:"5rem",right:"1rem",width:"min(430px,calc(100vw - 2rem))",maxHeight:"calc(100vh - 6rem)",overflow:"auto",zIndex:10001,background:"rgba(15,16,20,.96)",color:"#f4f4f5",border:"1px solid rgba(255,255,255,.14)",borderRadius:16,boxShadow:"0 20px 60px rgba(0,0,0,.45)",padding:16,fontFamily:"system-ui,sans-serif"};
const button={border:"1px solid rgba(255,255,255,.16)",background:"rgba(255,255,255,.07)",color:"inherit",borderRadius:9,padding:"7px 10px",cursor:"pointer"};
const card={border:"1px solid rgba(255,255,255,.1)",borderRadius:12,padding:10,marginTop:9,background:"rgba(255,255,255,.035)"};
function wsUrl(){const proto=location.protocol==="https:"?"wss":"ws";return proto+"://"+location.host+"/ws/realtime";}
function send(socket,msg){if(socket?.readyState===WebSocket.OPEN)socket.send(JSON.stringify(msg));}

export function RealtimeStrategy(){
 const [open,setOpen]=useState(false),[mode,setMode]=useState("single"),[socket,setSocket]=useState(null),[connected,setConnected]=useState(false),[roomId,setRoomId]=useState(""),[room,setRoom]=useState(null),[playerId,setPlayerId]=useState(""),[playerName,setPlayerName]=useState("Player"),[country,setCountry]=useState("GBR"),[joinId,setJoinId]=useState(""),[joinCountry,setJoinCountry]=useState("FRA"),[error,setError]=useState(""),[chatText,setChatText]=useState("");
 const socketRef=useRef(null);
 const connect=()=>{if(socketRef.current)return;setError("");const s=new WebSocket(wsUrl());socketRef.current=s;s.onopen=()=>{setConnected(true);setSocket(s)};s.onclose=()=>{setConnected(false);setSocket(null);socketRef.current=null};s.onerror=()=>setError("No se pudo conectar con el servidor realtime.");s.onmessage=event=>{try{const m=JSON.parse(event.data);if(m.type==="ROOM_CREATED"||m.type==="ROOM_JOINED"){setRoomId(m.roomId);setPlayerId(m.playerId);localStorage.setItem("oh:rt:playerId",m.playerId);localStorage.setItem("oh:rt:roomId",m.roomId);setRoom(m.snapshot)}else if(m.type==="SNAPSHOT")setRoom(m.snapshot);else if(m.type==="TIME_UPDATE")setRoom(r=>r?{...r,clock:m.clock}:r);else if(m.type==="WORLD_UPDATE")setRoom(r=>r?{...r,events:m.events||r.events,notifications:m.notifications||r.notifications}:r);else if(["BUILDING_UPDATE","RESEARCH_UPDATE","UNIT_UPDATE","EVENT_RESOLVED"].includes(m.type))setRoom(r=>r?{...r,...(m.snapshot||{}),countries:{...(r.countries||{}),...((m.snapshot||{}).countries||{})}}:r);else if(m.type==="DIPLOMACY_REQUEST")setRoom(r=>r?{...r,diplomacyRequests:[...(r.diplomacyRequests||[]),m.request]}:r);else if(m.type==="DIPLOMACY_RESPONSE")setRoom(r=>r?{...r,diplomacyRequests:(r.diplomacyRequests||[]).map(x=>x.id===m.request.id?m.request:x)}:r);else if(m.type==="NOTIFICATION")setRoom(r=>r?{...r,chat:m.notification.kind==="CHAT"?[...(r.chat||[]),m.notification].slice(-200):r.chat,notifications:[m.notification,...(r.notifications||[])].slice(0,30)}:r);else if(m.type==="ERROR")setError(m.error||"Servidor rechazó la operación.")}catch{setError("Respuesta realtime inválida.")}}};
 useEffect(()=>()=>socketRef.current?.close(),[]);// connect() is intentionally stable through the socket ref; reopening the HUD must not create duplicate sockets.\n // eslint-disable-next-line react-hooks/exhaustive-deps\n useEffect(()=>{if(open)connect()},[open]);
 const myPlayer=room?.players?.[playerId],myCountry=room?.countries?.[myPlayer?.countryCode||country],pendingEvents=(room?.events||[]).filter(e=>e.status==="pending"&&e.countryCode===myPlayer?.countryCode),techActive=myCountry?.research?.active,roomPlayers=Object.values(room?.players||{});
 const command=(action,payload)=>{setError("");send(socket,{type:"COMMAND",action,payload})};
 const create=()=>send(socket,{type:"CREATE_ROOM",mode,name:"Realtime Campaign",playerName,countryCode:country});
 const join=()=>send(socket,{type:"JOIN_ROOM",roomId:joinId.trim(),playerId:localStorage.getItem("oh:rt:playerId")||undefined,playerName,countryCode:joinCountry});
 const share=async()=>{try{await navigator.clipboard.writeText(roomId);setError("ID de sala copiado.")}catch{setError(roomId)}};
 const selectedUnit=myCountry?.units?.[0];
 return <><button type="button" onClick={()=>setOpen(v=>!v)} style={{...button,position:"fixed",right:"1rem",bottom:"5.5rem",zIndex:10000,background:open?"rgba(255,255,255,.16)":"rgba(15,16,20,.82)"}}>{room?"Realtime · "+room.clock.date:"Realtime"}</button>
 {open&&<div style={panel}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><div><strong style={{fontSize:18}}>Historia en tiempo real</strong><div style={{opacity:.65,fontSize:12}}>Servidor autoritativo · 1920-01-01</div></div><button style={button} onClick={()=>setOpen(false)}>×</button></div>
 {!room&&<div style={card}><label style={{display:"block",marginBottom:8}}>Nombre<input value={playerName} onChange={e=>setPlayerName(e.target.value.slice(0,40))} style={{width:"100%",boxSizing:"border-box",marginTop:4,padding:7,borderRadius:7}}/></label><label style={{display:"block",marginBottom:8}}>País<select value={country} onChange={e=>setCountry(e.target.value)} style={{width:"100%",padding:7}}>{countries.map(([c,n])=><option key={c} value={c}>{n}</option>)}</select></label><div style={{display:"flex",gap:6,marginBottom:8}}><button style={{...button,flex:1,opacity:mode==="single"?1:.6}} onClick={()=>setMode("single")}>Individual + IA</button><button style={{...button,flex:1,opacity:mode==="multi"?1:.6}} onClick={()=>setMode("multi")}>Multijugador</button></div><button style={{...button,width:"100%"}} onClick={create} disabled={!connected}>Crear sala</button><div style={{margin:"14px 0",opacity:.5,textAlign:"center"}}>o</div><label style={{display:"block",marginBottom:8}}>ID de sala<input value={joinId} onChange={e=>setJoinId(e.target.value)} placeholder="rt-..." style={{width:"100%",boxSizing:"border-box",marginTop:4,padding:7,borderRadius:7}}/></label><label style={{display:"block",marginBottom:8}}>País al unirse<select value={joinCountry} onChange={e=>setJoinCountry(e.target.value)} style={{width:"100%",padding:7}}>{countries.map(([c,n])=><option key={c} value={c}>{n}</option>)}</select></label><button style={{...button,width:"100%"}} onClick={join} disabled={!connected||!joinId.trim()}>Unirse a multijugador</button><div style={{fontSize:11,opacity:.6,marginTop:8}}>{connected?"Conectado al servidor.":"Conectando..."}</div><div style={{fontSize:11,opacity:.6,marginTop:5}}>Puedes reutilizar tu identidad guardada para reconectar una sala.</div></div>}
 {room&&<><div style={{...card,display:"flex",justifyContent:"space-between",gap:8,alignItems:"center"}}><div><div style={{fontSize:28,fontVariantNumeric:"tabular-nums"}}>{room.clock.date}</div><div style={{opacity:.65}}>Velocidad x{room.clock.speed} · {myPlayer?.countryCode} · {roomPlayers.length} jugador(es)</div></div><div style={{display:"flex",gap:5,flexWrap:"wrap",justifyContent:"flex-end"}}>{SPEEDS.map(s=><button key={s} style={button} onClick={()=>command(s===0?"PAUSE":"SET_SPEED",{speed:s})}>{s===0?"Ⅱ":"x"+s}</button>)}</div></div>
 <div style={{...card,display:"grid",gridTemplateColumns:"1fr 1fr",gap:7}}>{["population","money","food","energy","rawMaterials","industrialCapacity"].map(k=><div key={k}><span style={{opacity:.6,fontSize:11}}>{k}</span><div>{Math.round(myCountry?.[k]||0).toLocaleString()}</div></div>)}</div>
 <div style={card}><strong>Construcción</strong><div style={{display:"flex",gap:6,flexWrap:"wrap",marginTop:8}}>{buildings.map(([id,label])=><button key={id} style={button} onClick={()=>command("BUILD",{type:id,level:1})}>{label}</button>)}</div><div style={{fontSize:12,opacity:.7,marginTop:8}}>{(myCountry?.constructionQueue||[]).map(x=>x.type+": "+Math.max(0,Math.round(x.remainingDays))+" días").join(" · ")||"Sin obras en cola"}</div></div>
 <div style={card}><strong>Investigación</strong><div style={{fontSize:12,opacity:.7,margin:"5px 0"}}>{techActive?"Investigando "+techActive.techId+": "+Math.max(0,Math.round(techActive.remainingDays))+" días":"Puntos: "+Math.round(myCountry?.researchPoints||0)}</div><div style={{display:"flex",gap:6,flexWrap:"wrap"}}>{techs.filter(([id])=>(myCountry?.research?.completed||[]).indexOf(id)<0).map(([id,label])=><button key={id} style={button} disabled={!!techActive} onClick={()=>command("RESEARCH",{techId:id})}>{label}</button>)}</div></div>
 <div style={card}><strong>Eventos / decisiones</strong>{pendingEvents.length===0?<div style={{opacity:.6,fontSize:12,marginTop:5}}>Bandeja vacía. El tiempo no se detiene.</div>:pendingEvents.slice(0,5).map(e=><div key={e.id} style={{marginTop:8}}><div><b>{e.title}</b> <span style={{opacity:.55}}>prioridad {e.priority}</span></div><div style={{fontSize:12,opacity:.7}}>{e.category+" · vence "+e.expiresAt}</div><div style={{display:"flex",gap:5,marginTop:5}}>{e.choices.map(c=><button key={c.id} style={button} onClick={()=>command("EVENT_CHOICE",{eventId:e.id,choiceId:c.id})}>{c.label}</button>)}</div></div>)}</div>
 <div style={card}><strong>Militar</strong>{selectedUnit?<><div style={{fontSize:12,marginTop:5}}>{selectedUnit.name+" · "+selectedUnit.type+" · fuerza "+Math.round(selectedUnit.strength)}</div><div style={{display:"flex",gap:5,marginTop:6}}><button style={button} onClick={()=>command("MOVE_UNIT",{unitId:selectedUnit.id,x:0,y:0})}>Mover a (0,0)</button><button style={button} onClick={()=>command("MOVE_UNIT",{unitId:selectedUnit.id,x:20,y:30})}>Mover a (20,30)</button></div></>:<div style={{opacity:.6}}>Sin unidades.</div>}</div>
 <div style={card}><strong>Diplomacia humana</strong><div style={{display:"flex",gap:5,marginTop:6}}><select id="rt-dip-target" style={{flex:1,padding:7}}>{countries.filter(([c])=>c!==myPlayer?.countryCode).map(([c,n])=><option key={c} value={c}>{n}</option>)}</select><button style={button} onClick={()=>{const target=document.getElementById("rt-dip-target")?.value;send(socket,{type:"DIPLOMACY_REQUEST",targetCountry:target,message:"Proposal from "+myPlayer?.countryCode})}}>Proponer</button></div>{(room.diplomacyRequests||[]).filter(r=>r.status==="pending"&&r.toCountry===myPlayer?.countryCode).map(r=><div key={r.id} style={{marginTop:7,fontSize:12}}>{r.fromCountry+": "+r.message}<div style={{display:"flex",gap:5,marginTop:4}}><button style={button} onClick={()=>send(socket,{type:"DIPLOMACY_RESPONSE",requestId:r.id,accepted:true})}>Aceptar</button><button style={button} onClick={()=>send(socket,{type:"DIPLOMACY_RESPONSE",requestId:r.id,accepted:false})}>Rechazar</button></div></div>)}</div>
 <div style={card}><strong>Chat humano</strong><div style={{maxHeight:100,overflow:"auto",fontSize:12,margin:"6px 0"}}>{(room.chat||[]).slice(-8).map(m=><div key={m.id}><b>{m.playerId===playerId?"Tú":m.playerId}</b>: {m.text}</div>)}</div><div style={{display:"flex",gap:5}}><input value={chatText} onChange={e=>setChatText(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&chatText.trim()){send(socket,{type:"CHAT",text:chatText});setChatText("")}}} style={{flex:1,padding:7,borderRadius:7}} placeholder="Mensaje..."/><button style={button} onClick={()=>{if(chatText.trim()){send(socket,{type:"CHAT",text:chatText});setChatText("")}}}>Enviar</button></div></div>
 <div style={card}><strong>Sala</strong><div style={{fontSize:12,opacity:.7}}>ID: {roomId}</div><button style={{...button,marginTop:6}} onClick={share}>Copiar ID</button></div></>}
 {error&&<div style={{marginTop:10,padding:9,borderRadius:9,background:"rgba(180,60,60,.18)",fontSize:12}}>{error}</div>}
 </div>}
 </>;
}
